name: Checkov

on:
  push:
    branches: [ developer, master ]
  pull_request:
    branches: [ developer, master ]

jobs:
  checkov-job:
    runs on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: juicy/
